### ISSUE TITLE
add_devices_to_group Module Sends Bad JSON

### ISSUE THREAD

**Issue by jjaswanson4** [ansible-collections/consoledot.edgemanagement#16]
##### SUMMARY
The 'add_devices_to_group' module returns a 400 when attempting to use: `"msg": "[POST] Error-400: {'Code': 'BAD_REQUEST', 'Status': 400, 'Title': 'invalid JSON request'}"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
consoedot.edgemanagement.add_devices_to_group

##### ANSIBLE VERSION
```
ansible [core 2.13.0]
  config file = /root/code/jdc/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
Collection                Version
------------------------- -------
consoledot.edgemanagement 0.1.1  
```

##### CONFIGURATION
```
GALAXY_IGNORE_CERTS(/root/code/jdc/ansible.cfg) = True
GALAXY_SERVER_LIST(/root/code/jdc/ansible.cfg) = ['rh-certified_repo', 'community_repo', 'published_repo', 'community_galaxy']
HOST_KEY_CHECKING(/root/code/jdc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.5 (Ootpa)

##### STEPS TO REPRODUCE
The following task is used as an example:
```yaml
    - name: add device to group
      consoledot.edgemanagement.add_devices_to_group:
        name: "{{ group_name }}"
        devices: "{{ device_id }}"
        state: "{{ group_membership_state | default('present') }}"
```

##### EXPECTED RESULTS
Device should be added to the group specified and Ansible should return "changed" (or ok if already present in group)

##### ACTUAL RESULTS
```
fatal: [edge-005056987837 -> console.redhat.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "devices": [
                "1911481"
            ],
            "name": "71d8",
            "state": "present"
        }
    },
    "msg": "[POST] Error-400: {'Code': 'BAD_REQUEST', 'Status': 400, 'Title': 'invalid JSON request'}"

```

#### NOTES
This may be due to Ansible sending strings instead of int, the following based off the uri module works;
```yaml
- name: add device to group
  ansible.builtin.uri:
    url: https://console.redhat.com/api/edge/v1/device-groups/{{ edge_management_group.content | from_json | json_query('data[0].DeviceGroup.ID') }}/devices
    method: POST
    body_format: json
    body: >
      {
        "ID": {{ edge_management_group.content | from_json | json_query('data[0].DeviceGroup.ID') | int }},
        "Devices": [
          {
            "ID": {{ device_info.content | from_json | json_query('data[0].Device.ID') | int }}
          }
        ]
      }
```
