### ISSUE TITLE
The groups Module Does Not Handle Spaces

### ISSUE THREAD

**Issue by jjaswanson4** [ansible-collections/consoledot.edgemanagement#19]
##### SUMMARY
When creating a group via the `groups` module, if the group has spaces the API request will fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`consoledot.edgemanagement.groups`

##### ANSIBLE VERSION

```
ansible [core 2.13.0]
  config file = /root/code/jdc/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /root/.ansible/collections/ansible_collections
Collection                Version
------------------------- -------
consoledot.edgemanagement 0.1.1  
```

##### CONFIGURATION

```
GALAXY_IGNORE_CERTS(/root/code/jdc/ansible.cfg) = True
GALAXY_SERVER_LIST(/root/code/jdc/ansible.cfg) = ['rh-certified_repo', 'community_repo', 'published_repo', 'community_galaxy']
HOST_KEY_CHECKING(/root/code/jdc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
Red Hat Enterprise Linux release 8.5 (Ootpa)
```

##### STEPS TO REPRODUCE
Attempt to create a group that has spaces in the name:
```yaml
- name: create group in Edge Management
  consoledot.edgemanagement.groups:
    name: "{{ edge_management_group }}"
    state: "{{ group_state | default('present') }}"
  loop_control:
    loop_var: edge_management_group
  loop:
    - test_group <-- succeeds
    - "test group" <-- fails
```

##### EXPECTED RESULTS
The group should be created.

##### ACTUAL RESULTS
```
{
  "postdata": {
    "name": "Process Control Systems",
    "type": "static"
  },
  "msg": "URL can't contain control characters. '/api/edge/v1/device-groups?name=Process Control Systems' (found at least ' ')",
  "invocation": {
    "module_args": {
      "name": "Process Control Systems",
      "state": "present"
    }
  },
  "_ansible_no_log": null,
  "changed": false,
  "edge_management_group": "Process Control Systems",
  "ansible_loop_var": "edge_management_group",
  "_ansible_item_label": "Process Control Systems"
}

```

#### NOTES
Edge Management/the API does accept group names with spaces in them, however when firing calls to the API the spaces must be replaced with '%20' for the call to succeed.

From the above, this should actually work: `'/api/edge/v1/device-groups?name=Process%20Control%20Systems'`
